# Default configuration for nios2-softmmu

CONFIG_NIOS2=y
CONFIG_PTIMER=y
CONFIG_SERIAL=y
CONFIG_PFLASH_CFI01=y
CONFIG_ALTERA=y
CONFIG_ALTERA_TIMER=y
CONFIG_ALTERA_JUART=y
CONFIG_FDT_GENERIC=y
CONFIG_LABX=y
